enum class NotificationType {
    UPDATE_ACTION,
    ADD_IMAGE,
    SELECT_IMAGE,
    DELETE_IMAGE,
    SCALE_UP_IMAGE,
    SCALE_DOWN_IMAGE,
    ROTATE_IMAGE_LEFT,
    ROTATE_IMAGE_RIGHT,
    TILE_MODE,
    RESET_IMAGE,
    CASCADE_MODE,
    ADD_MULTIPLE_IMAGES
}